name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t xv6-maman03 .

      - name: Validate xv6 directory
        run: docker run --rm --platform linux/amd64 xv6-maman03 test -d /xv6

      - name: Validate xv6 Makefile
        run: docker run --rm --platform linux/amd64 xv6-maman03 test -f /xv6/Makefile
